name: Enforce Branch Name

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release)/[a-zA-Z0-9_-]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow naming conventions."
            exit 1
          fi
