name: Enforce Branch Naming Convention

# Trigger on any push to branches other than the default branch (like 'main' or 'master')
on:
  push:
    branches:
      - '*'
      - '!main'  # Ignore the main branch (adjust based on your default branch)

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          # Define your branch naming pattern (e.g., feature/, bugfix/, hotfix/, or release/)
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release)/[a-zA-Z0-9_-]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention."
            echo "Please use one of the following prefixes: 'feature/', 'bugfix/', 'hotfix/', or 'release/'."
            exit 1
          fi
